// AUTO-GENERATED snapshot of the 24 cube uniques (EN). Images live in /public/uniques.
// These cards aren't in the community set files and were previously fetched live from
// api.altered.gg. That API is being retired, so we bundle the data + images locally to
// keep LuigiNico's cube working offline-forever. Regenerate by re-running the snapshot
// script if a unique is swapped. Non-EN locales still fall back to the live API.
export const UNIQUES_EN = {
  'ALT_CORE_B_AX_04_U_1437': { reference: 'ALT_CORE_B_AX_04_U_1437', name: 'Kelon Elemental', faction: 'AX', factionName: 'Axiom', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_AX_04_U_1437.jpg', cardType: 'CHARACTER', mainCost: 3, recallCost: 1, forestPower: 1, mountainPower: 2, oceanPower: 2 },
  'ALT_CYCLONE_B_AX_66_U_6442': { reference: 'ALT_CYCLONE_B_AX_66_U_6442', name: 'Gavroche', faction: 'AX', factionName: 'Axiom', rarity: 'U', imagePath: '/uniques/ALT_CYCLONE_B_AX_66_U_6442.jpg', cardType: 'CHARACTER', mainCost: 2, recallCost: 2, forestPower: 2, mountainPower: 0, oceanPower: 2 },
  'ALT_CORE_B_AX_06_U_383': { reference: 'ALT_CORE_B_AX_06_U_383', name: 'Ogun', faction: 'AX', factionName: 'Axiom', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_AX_06_U_383.jpg', cardType: 'CHARACTER', mainCost: 3, recallCost: 1, forestPower: 1, mountainPower: 0, oceanPower: 1 },
  'ALT_CORE_B_OR_09_U_894': { reference: 'ALT_CORE_B_OR_09_U_894', name: 'The Frog Prince', faction: 'OR', factionName: 'Ordis', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_OR_09_U_894.jpg', cardType: 'CHARACTER', mainCost: 2, recallCost: 1, forestPower: 2, mountainPower: 2, oceanPower: 2 },
  'ALT_CYCLONE_B_YZ_73_U_4784': { reference: 'ALT_CYCLONE_B_YZ_73_U_4784', name: 'Alelo, Eerie Leviathan', faction: 'AX', factionName: 'Axiom', rarity: 'U', imagePath: '/uniques/ALT_CYCLONE_B_YZ_73_U_4784.jpg', cardType: 'CHARACTER', mainCost: 4, recallCost: 4, forestPower: 1, mountainPower: 1, oceanPower: 1 },
  'ALT_COREKS_B_AX_07_U_101': { reference: 'ALT_COREKS_B_AX_07_U_101', name: 'Foundry Mechanic', faction: 'AX', factionName: 'Axiom', rarity: 'U', imagePath: '/uniques/ALT_COREKS_B_AX_07_U_101.jpg', cardType: 'CHARACTER', mainCost: 2, recallCost: 1, forestPower: 0, mountainPower: 2, oceanPower: 0 },
  'ALT_CORE_B_BR_18_U_82': { reference: 'ALT_CORE_B_BR_18_U_82', name: 'Sun Wukong', faction: 'BR', factionName: 'Bravos', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_BR_18_U_82.jpg', cardType: 'CHARACTER', mainCost: 2, recallCost: 3, forestPower: 3, mountainPower: 3, oceanPower: 2 },
  'ALT_CORE_B_AX_16_U_2856': { reference: 'ALT_CORE_B_AX_16_U_2856', name: 'Foundry Armorer', faction: 'BR', factionName: 'Bravos', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_AX_16_U_2856.jpg', cardType: 'CHARACTER', mainCost: 4, recallCost: 3, forestPower: 1, mountainPower: 3, oceanPower: 1 },
  'ALT_CYCLONE_B_YZ_70_U_6595': { reference: 'ALT_CYCLONE_B_YZ_70_U_6595', name: 'Suha, Qorgan Operative', faction: 'BR', factionName: 'Bravos', rarity: 'U', imagePath: '/uniques/ALT_CYCLONE_B_YZ_70_U_6595.jpg', cardType: 'CHARACTER', mainCost: 3, recallCost: 3, forestPower: 4, mountainPower: 1, oceanPower: 2 },
  'ALT_BISE_B_BR_52_U_978': { reference: 'ALT_BISE_B_BR_52_U_978', name: 'Talarian Skater', faction: 'BR', factionName: 'Bravos', rarity: 'U', imagePath: '/uniques/ALT_BISE_B_BR_52_U_978.jpg', cardType: 'CHARACTER', mainCost: 3, recallCost: 4, forestPower: 3, mountainPower: 4, oceanPower: 1 },
  'ALT_CYCLONE_B_BR_72_U_10046': { reference: 'ALT_CYCLONE_B_BR_72_U_10046', name: 'Wingsuit Jumper', faction: 'BR', factionName: 'Bravos', rarity: 'U', imagePath: '/uniques/ALT_CYCLONE_B_BR_72_U_10046.jpg', cardType: 'CHARACTER', mainCost: 3, recallCost: 3, forestPower: 2, mountainPower: 3, oceanPower: 3 },
  'ALT_CYCLONE_B_BR_75_U_6544': { reference: 'ALT_CYCLONE_B_BR_75_U_6544', name: 'The Hare', faction: 'BR', factionName: 'Bravos', rarity: 'U', imagePath: '/uniques/ALT_CYCLONE_B_BR_75_U_6544.jpg', cardType: 'CHARACTER', mainCost: 4, recallCost: 4, forestPower: 5, mountainPower: 4, oceanPower: 5 },
  'ALT_CORE_B_LY_08_U_2678': { reference: 'ALT_CORE_B_LY_08_U_2678', name: 'Lyra Skald', faction: 'LY', factionName: 'Lyra', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_LY_08_U_2678.jpg', cardType: 'CHARACTER', mainCost: 2, recallCost: 3, forestPower: 3, mountainPower: 0, oceanPower: 1 },
  'ALT_CORE_B_LY_07_U_1272': { reference: 'ALT_CORE_B_LY_07_U_1272', name: 'Hathor', faction: 'LY', factionName: 'Lyra', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_LY_07_U_1272.jpg', cardType: 'CHARACTER', mainCost: 3, recallCost: 3, forestPower: 4, mountainPower: 0, oceanPower: 4 },
  'ALT_CORE_B_BR_19_U_1130': { reference: 'ALT_CORE_B_BR_19_U_1130', name: 'Mighty Jinn', faction: 'LY', factionName: 'Lyra', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_BR_19_U_1130.jpg', cardType: 'CHARACTER', mainCost: 4, recallCost: 4, forestPower: 5, mountainPower: 2, oceanPower: 0 },
  'ALT_CYCLONE_B_OR_70_U_6311': { reference: 'ALT_CYCLONE_B_OR_70_U_6311', name: 'Melusine', faction: 'LY', factionName: 'Lyra', rarity: 'U', imagePath: '/uniques/ALT_CYCLONE_B_OR_70_U_6311.jpg', cardType: 'CHARACTER', mainCost: 3, recallCost: 3, forestPower: 0, mountainPower: 3, oceanPower: 4 },
  'ALT_BISE_B_LY_50_U_6263': { reference: 'ALT_BISE_B_LY_50_U_6263', name: 'BLISS Fan', faction: 'LY', factionName: 'Lyra', rarity: 'U', imagePath: '/uniques/ALT_BISE_B_LY_50_U_6263.jpg', cardType: 'CHARACTER', mainCost: 2, recallCost: 3, forestPower: 0, mountainPower: 2, oceanPower: 2 },
  'ALT_CORE_B_LY_14_U_2369': { reference: 'ALT_CORE_B_LY_14_U_2369', name: 'Lyra Cloth Dancer', faction: 'LY', factionName: 'Lyra', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_LY_14_U_2369.jpg', cardType: 'CHARACTER', mainCost: 2, recallCost: 2, forestPower: 3, mountainPower: 3, oceanPower: 0 },
  'ALT_CORE_B_MU_11_U_6804': { reference: 'ALT_CORE_B_MU_11_U_6804', name: 'Inari', faction: 'MU', factionName: 'Muna', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_MU_11_U_6804.jpg', cardType: 'CHARACTER', mainCost: 4, recallCost: 3, forestPower: 0, mountainPower: 4, oceanPower: 3 },
  'ALT_ALIZE_B_MU_36_U_10756': { reference: 'ALT_ALIZE_B_MU_36_U_10756', name: 'Yeti', faction: 'MU', factionName: 'Muna', rarity: 'U', imagePath: '/uniques/ALT_ALIZE_B_MU_36_U_10756.jpg', cardType: 'CHARACTER', mainCost: 4, recallCost: 4, forestPower: 3, mountainPower: 2, oceanPower: 3 },
  'ALT_CORE_B_MU_05_U_3773': { reference: 'ALT_CORE_B_MU_05_U_3773', name: 'Kitsune', faction: 'MU', factionName: 'Muna', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_MU_05_U_3773.jpg', cardType: 'CHARACTER', mainCost: 3, recallCost: 2, forestPower: 0, mountainPower: 4, oceanPower: 1 },
  'ALT_COREKS_B_MU_09_U_4554': { reference: 'ALT_COREKS_B_MU_09_U_4554', name: 'Kodama', faction: 'MU', factionName: 'Muna', rarity: 'U', imagePath: '/uniques/ALT_COREKS_B_MU_09_U_4554.jpg', cardType: 'CHARACTER', mainCost: 3, recallCost: 3, forestPower: 2, mountainPower: 4, oceanPower: 3 },
  'ALT_CYCLONE_B_LY_67_U_6544': { reference: 'ALT_CYCLONE_B_LY_67_U_6544', name: 'Sticky Shroom', faction: 'MU', factionName: 'Muna', rarity: 'U', imagePath: '/uniques/ALT_CYCLONE_B_LY_67_U_6544.jpg', cardType: 'CHARACTER', mainCost: 2, recallCost: 2, forestPower: 2, mountainPower: 0, oceanPower: 0 },
  'ALT_CORE_B_MU_18_U_6578': { reference: 'ALT_CORE_B_MU_18_U_6578', name: 'Parvati', faction: 'MU', factionName: 'Muna', rarity: 'U', imagePath: '/uniques/ALT_CORE_B_MU_18_U_6578.jpg', cardType: 'CHARACTER', mainCost: 4, recallCost: 3, forestPower: 4, mountainPower: 0, oceanPower: 3 },
}

